# This image runs the dcos-cli test suite.

FROM ubuntu:15.04
MAINTAINER support@mesosphere.com

RUN apt-get update && apt-get install -y \
  httpie \
  jq \
  make \
  build-essential \
  libssl-dev \
  libffi-dev \
  python-dev \
  python3-pip \
  python3-venv \
  openssh-client \
  git \
  sudo

ADD . /dcos-cli
WORKDIR /dcos-cli
