# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mesos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mesos.proto',
  package='mesos',
  serialized_pb=_b('\n\x0bmesos.proto\x12\x05mesos\"f\n\x07TtyInfo\x12.\n\x0bwindow_size\x18\x01 \x01(\x0b\x32\x19.mesos.TtyInfo.WindowSize\x1a+\n\nWindowSize\x12\x0c\n\x04rows\x18\x01 \x02(\r\x12\x0f\n\x07\x63olumns\x18\x02 \x02(\r\"\xa1\x03\n\tProcessIO\x12#\n\x04type\x18\x01 \x01(\x0e\x32\x15.mesos.ProcessIO.Type\x12#\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x15.mesos.ProcessIO.Data\x12)\n\x07\x63ontrol\x18\x03 \x01(\x0b\x32\x18.mesos.ProcessIO.Control\x1av\n\x04\x44\x61ta\x12(\n\x04type\x18\x01 \x01(\x0e\x32\x1a.mesos.ProcessIO.Data.Type\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"6\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05STDIN\x10\x01\x12\n\n\x06STDOUT\x10\x02\x12\n\n\x06STDERR\x10\x03\x1a{\n\x07\x43ontrol\x12+\n\x04type\x18\x01 \x01(\x0e\x32\x1d.mesos.ProcessIO.Control.Type\x12 \n\x08tty_info\x18\x02 \x01(\x0b\x32\x0e.mesos.TtyInfo\"!\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08TTY_INFO\x10\x01\"*\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04\x44\x41TA\x10\x01\x12\x0b\n\x07\x43ONTROL\x10\x02\"@\n\x0b\x43ontainerID\x12\r\n\x05value\x18\x01 \x02(\t\x12\"\n\x06parent\x18\x02 \x01(\x0b\x32\x12.mesos.ContainerID\"\x86\x02\n\x0b\x43ommandInfo\x12$\n\x04uris\x18\x01 \x03(\x0b\x32\x16.mesos.CommandInfo.URI\x12\'\n\x0b\x65nvironment\x18\x02 \x01(\x0b\x32\x12.mesos.Environment\x12\x13\n\x05shell\x18\x06 \x01(\x08:\x04true\x12\r\n\x05value\x18\x03 \x01(\t\x12\x11\n\targuments\x18\x07 \x03(\t\x12\x0c\n\x04user\x18\x05 \x01(\t\x1a\x63\n\x03URI\x12\r\n\x05value\x18\x01 \x02(\t\x12\x12\n\nexecutable\x18\x02 \x01(\x08\x12\x15\n\x07\x65xtract\x18\x03 \x01(\x08:\x04true\x12\r\n\x05\x63\x61\x63he\x18\x04 \x01(\x08\x12\x13\n\x0boutput_file\x18\x05 \x01(\t\"f\n\x0b\x45nvironment\x12.\n\tvariables\x18\x01 \x03(\x0b\x32\x1b.mesos.Environment.Variable\x1a\'\n\x08Variable\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\tB\x1a\n\x10org.apache.mesosB\x06Protos')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PROCESSIO_DATA_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='mesos.ProcessIO.Data.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STDIN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STDOUT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STDERR', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=321,
  serialized_end=375,
)
_sym_db.RegisterEnumDescriptor(_PROCESSIO_DATA_TYPE)

_PROCESSIO_CONTROL_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='mesos.ProcessIO.Control.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TTY_INFO', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=467,
  serialized_end=500,
)
_sym_db.RegisterEnumDescriptor(_PROCESSIO_CONTROL_TYPE)

_PROCESSIO_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='mesos.ProcessIO.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATA', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTROL', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=502,
  serialized_end=544,
)
_sym_db.RegisterEnumDescriptor(_PROCESSIO_TYPE)


_TTYINFO_WINDOWSIZE = _descriptor.Descriptor(
  name='WindowSize',
  full_name='mesos.TtyInfo.WindowSize',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='mesos.TtyInfo.WindowSize.rows', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='columns', full_name='mesos.TtyInfo.WindowSize.columns', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=124,
)

_TTYINFO = _descriptor.Descriptor(
  name='TtyInfo',
  full_name='mesos.TtyInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='window_size', full_name='mesos.TtyInfo.window_size', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TTYINFO_WINDOWSIZE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=124,
)


_PROCESSIO_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='mesos.ProcessIO.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='mesos.ProcessIO.Data.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='mesos.ProcessIO.Data.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PROCESSIO_DATA_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=375,
)

_PROCESSIO_CONTROL = _descriptor.Descriptor(
  name='Control',
  full_name='mesos.ProcessIO.Control',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='mesos.ProcessIO.Control.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tty_info', full_name='mesos.ProcessIO.Control.tty_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PROCESSIO_CONTROL_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=500,
)

_PROCESSIO = _descriptor.Descriptor(
  name='ProcessIO',
  full_name='mesos.ProcessIO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='mesos.ProcessIO.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='mesos.ProcessIO.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='control', full_name='mesos.ProcessIO.control', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PROCESSIO_DATA, _PROCESSIO_CONTROL, ],
  enum_types=[
    _PROCESSIO_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=544,
)


_CONTAINERID = _descriptor.Descriptor(
  name='ContainerID',
  full_name='mesos.ContainerID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='mesos.ContainerID.value', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parent', full_name='mesos.ContainerID.parent', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=546,
  serialized_end=610,
)


_COMMANDINFO_URI = _descriptor.Descriptor(
  name='URI',
  full_name='mesos.CommandInfo.URI',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='mesos.CommandInfo.URI.value', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='executable', full_name='mesos.CommandInfo.URI.executable', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extract', full_name='mesos.CommandInfo.URI.extract', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cache', full_name='mesos.CommandInfo.URI.cache', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_file', full_name='mesos.CommandInfo.URI.output_file', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=776,
  serialized_end=875,
)

_COMMANDINFO = _descriptor.Descriptor(
  name='CommandInfo',
  full_name='mesos.CommandInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uris', full_name='mesos.CommandInfo.uris', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='environment', full_name='mesos.CommandInfo.environment', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shell', full_name='mesos.CommandInfo.shell', index=2,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='mesos.CommandInfo.value', index=3,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='arguments', full_name='mesos.CommandInfo.arguments', index=4,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user', full_name='mesos.CommandInfo.user', index=5,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_COMMANDINFO_URI, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=613,
  serialized_end=875,
)


_ENVIRONMENT_VARIABLE = _descriptor.Descriptor(
  name='Variable',
  full_name='mesos.Environment.Variable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='mesos.Environment.Variable.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='mesos.Environment.Variable.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=940,
  serialized_end=979,
)

_ENVIRONMENT = _descriptor.Descriptor(
  name='Environment',
  full_name='mesos.Environment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='variables', full_name='mesos.Environment.variables', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ENVIRONMENT_VARIABLE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=877,
  serialized_end=979,
)

_TTYINFO_WINDOWSIZE.containing_type = _TTYINFO
_TTYINFO.fields_by_name['window_size'].message_type = _TTYINFO_WINDOWSIZE
_PROCESSIO_DATA.fields_by_name['type'].enum_type = _PROCESSIO_DATA_TYPE
_PROCESSIO_DATA.containing_type = _PROCESSIO
_PROCESSIO_DATA_TYPE.containing_type = _PROCESSIO_DATA
_PROCESSIO_CONTROL.fields_by_name['type'].enum_type = _PROCESSIO_CONTROL_TYPE
_PROCESSIO_CONTROL.fields_by_name['tty_info'].message_type = _TTYINFO
_PROCESSIO_CONTROL.containing_type = _PROCESSIO
_PROCESSIO_CONTROL_TYPE.containing_type = _PROCESSIO_CONTROL
_PROCESSIO.fields_by_name['type'].enum_type = _PROCESSIO_TYPE
_PROCESSIO.fields_by_name['data'].message_type = _PROCESSIO_DATA
_PROCESSIO.fields_by_name['control'].message_type = _PROCESSIO_CONTROL
_PROCESSIO_TYPE.containing_type = _PROCESSIO
_CONTAINERID.fields_by_name['parent'].message_type = _CONTAINERID
_COMMANDINFO_URI.containing_type = _COMMANDINFO
_COMMANDINFO.fields_by_name['uris'].message_type = _COMMANDINFO_URI
_COMMANDINFO.fields_by_name['environment'].message_type = _ENVIRONMENT
_ENVIRONMENT_VARIABLE.containing_type = _ENVIRONMENT
_ENVIRONMENT.fields_by_name['variables'].message_type = _ENVIRONMENT_VARIABLE
DESCRIPTOR.message_types_by_name['TtyInfo'] = _TTYINFO
DESCRIPTOR.message_types_by_name['ProcessIO'] = _PROCESSIO
DESCRIPTOR.message_types_by_name['ContainerID'] = _CONTAINERID
DESCRIPTOR.message_types_by_name['CommandInfo'] = _COMMANDINFO
DESCRIPTOR.message_types_by_name['Environment'] = _ENVIRONMENT

TtyInfo = _reflection.GeneratedProtocolMessageType('TtyInfo', (_message.Message,), dict(

  WindowSize = _reflection.GeneratedProtocolMessageType('WindowSize', (_message.Message,), dict(
    DESCRIPTOR = _TTYINFO_WINDOWSIZE,
    __module__ = 'mesos_pb2'
    # @@protoc_insertion_point(class_scope:mesos.TtyInfo.WindowSize)
    ))
  ,
  DESCRIPTOR = _TTYINFO,
  __module__ = 'mesos_pb2'
  # @@protoc_insertion_point(class_scope:mesos.TtyInfo)
  ))
_sym_db.RegisterMessage(TtyInfo)
_sym_db.RegisterMessage(TtyInfo.WindowSize)

ProcessIO = _reflection.GeneratedProtocolMessageType('ProcessIO', (_message.Message,), dict(

  Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
    DESCRIPTOR = _PROCESSIO_DATA,
    __module__ = 'mesos_pb2'
    # @@protoc_insertion_point(class_scope:mesos.ProcessIO.Data)
    ))
  ,

  Control = _reflection.GeneratedProtocolMessageType('Control', (_message.Message,), dict(
    DESCRIPTOR = _PROCESSIO_CONTROL,
    __module__ = 'mesos_pb2'
    # @@protoc_insertion_point(class_scope:mesos.ProcessIO.Control)
    ))
  ,
  DESCRIPTOR = _PROCESSIO,
  __module__ = 'mesos_pb2'
  # @@protoc_insertion_point(class_scope:mesos.ProcessIO)
  ))
_sym_db.RegisterMessage(ProcessIO)
_sym_db.RegisterMessage(ProcessIO.Data)
_sym_db.RegisterMessage(ProcessIO.Control)

ContainerID = _reflection.GeneratedProtocolMessageType('ContainerID', (_message.Message,), dict(
  DESCRIPTOR = _CONTAINERID,
  __module__ = 'mesos_pb2'
  # @@protoc_insertion_point(class_scope:mesos.ContainerID)
  ))
_sym_db.RegisterMessage(ContainerID)

CommandInfo = _reflection.GeneratedProtocolMessageType('CommandInfo', (_message.Message,), dict(

  URI = _reflection.GeneratedProtocolMessageType('URI', (_message.Message,), dict(
    DESCRIPTOR = _COMMANDINFO_URI,
    __module__ = 'mesos_pb2'
    # @@protoc_insertion_point(class_scope:mesos.CommandInfo.URI)
    ))
  ,
  DESCRIPTOR = _COMMANDINFO,
  __module__ = 'mesos_pb2'
  # @@protoc_insertion_point(class_scope:mesos.CommandInfo)
  ))
_sym_db.RegisterMessage(CommandInfo)
_sym_db.RegisterMessage(CommandInfo.URI)

Environment = _reflection.GeneratedProtocolMessageType('Environment', (_message.Message,), dict(

  Variable = _reflection.GeneratedProtocolMessageType('Variable', (_message.Message,), dict(
    DESCRIPTOR = _ENVIRONMENT_VARIABLE,
    __module__ = 'mesos_pb2'
    # @@protoc_insertion_point(class_scope:mesos.Environment.Variable)
    ))
  ,
  DESCRIPTOR = _ENVIRONMENT,
  __module__ = 'mesos_pb2'
  # @@protoc_insertion_point(class_scope:mesos.Environment)
  ))
_sym_db.RegisterMessage(Environment)
_sym_db.RegisterMessage(Environment.Variable)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\020org.apache.mesosB\006Protos'))
# @@protoc_insertion_point(module_scope)
