// Code generated by goderive DO NOT EDIT.

package plugin

// deriveDeepCopy recursively copies the contents of src into dst.
func deriveDeepCopy(dst, src *Plugin) {
	dst.Name = src.Name
	if src.Commands == nil {
		dst.Commands = nil
	} else {
		if dst.Commands != nil {
			if len(src.Commands) > len(dst.Commands) {
				if cap(dst.Commands) >= len(src.Commands) {
					dst.Commands = (dst.Commands)[:len(src.Commands)]
				} else {
					dst.Commands = make([]Command, len(src.Commands))
				}
			} else if len(src.Commands) < len(dst.Commands) {
				dst.Commands = (dst.Commands)[:len(src.Commands)]
			}
		} else {
			dst.Commands = make([]Command, len(src.Commands))
		}
		copy(dst.Commands, src.Commands)
	}
}
